### ISSUE TITLE
can't make it work

### ISSUE THREAD

**Issue by enriqueto** [SBCGames/Spriter-Player-for-Phaser#16]
I need to animate 2 characters with the names of Gwen and Christian, I've packed all the png's with texture packer. Would you mind taking a look?

[character files](https://www.dropbox.com/s/wb4oyyth5b914vd/clients.zip?dl=0)

**Comment by SBCGames** [comment]
- can you specify, what is broke?
- could you please send me also packed Spriter project, so I can see how it should look?

**Comment by enriqueto** [comment]
[](https://www.dropbox.com/s/glsqvny7i2jdry1/test-spriter.zip?dl=0)

I've done this project for you. Our designer wants to have 2 different clients sharing 1 animation. I don't know how to implement that.

**Comment by SBCGames** [comment]
[spriter-test.zip](https://github.com/SBCGames/Spriter-Player-for-Phaser/files/658804/spriter-test.zip)

In attachment you will find working project. There are two characters on screen - guy and girl. Problems were:
 - in Client class you disabled visibility of Spriter character (this.animatedClientGroup.visible = false;),
 - animation was too fast - I changed speed from 100% to 10%,
 - use latest spriter.min.js from GitHub project build folder (you had some older one). In new I changed little eImageNameType enum. It has ORIGINAL instead of FILL_PATH_WITH_EXTENSION (btw, I think you were only person with that version as it was created during last time we were solving some problems).  You always need to match image name between sprite in atlas and sprite in Spriter - this is what eImageNameType is for. It says what to do with sprite name in Spriter file (ORIGINAL = keep it, NAME_AND_EXTENSION = keep name and extension, but get rid of path, ...),
 - second character (girl) is made with charmap. Its animation is broken (shifted sprites). If you want to use charmaps in Spriter, then your replacement sprites have to have the same size (beacuase original pivots / positions / ... are used, only sprite is changed) Currently, those sprites have different size,
 - to use charmap, call pushCharMap(charMapName) - push means, charmaps can be stacked!!! You can make charmaps for changing T-shirt and other for hats or whatever and then make character with red T-shirt and funny hat like this: pushCharMap(redShirt); pushCharMap(funnyHat);,
 - last pushed charmap is "strongest". Pushing pushCharMap(blueShirt); to character above means, that redShirt will be overriden with blue one,
 - to clear stack of charmaps on character, call clearCharMaps();

**Comment by enriqueto** [comment]
thanks!

I can make it work now. The designer is using png's the same size now.
