### ISSUE TITLE
Detect touch on playing animation

### ISSUE THREAD

**Issue by udsplashmath** [SBCGames/Spriter-Player-for-Phaser#27]
Can I get touch events on a playing spriter animation along with the bounding box?
I am collecting information before diving in? I am using Phaser 3 and porting from Phaser-CE

**Comment by SBCGames** [comment]
With Phaser 2 you can use Phaser input capabilities. Spriter.Group is Phaser.Group, so I would add empty sprite, to Spriter.Group (with required shape and size) and enabled input on it.
 Adding input directly to sprites used by animation in Spriter.Group is not possible, because Spriter.Group maintains pool of them and you cannot be sure, that sprite used, for example, for character body is not used for head in next frame.
