### ISSUE TITLE
Switch textures 

### ISSUE THREAD

**Issue by enriqueto** [SBCGames/Spriter-Player-for-Phaser#4]
This feature is implemented in dragon bones and is very practical. For example, you could change the face expression or some parts of a character:

https://dragonbones.github.io/features.html

see "Dynamic Texture Switching". 

I could implement that if you give me some directions.

**Comment by SBCGames** [comment]
Spriter Pro has this feature. There is now big discount, so I purchased one. It means, I will probably implement it in future (when I need it for some of my games).

It maps new folder/file to original folder/file

As a quick solution, I would add some "convertor" method to line 38 of SpriterObject.ts file:
`this._sprite.frameName = file.name;`
 Instead of assigning file name directly, pass it to some convertor and return alternative sprite (if found). If not found return the original one.

 It already has reference to Spriter object that holds animation structure. So, I would add some char maps into this Spriter object as well as that convertor method.

**Comment by enriqueto** [comment]
Sounds good with the convertor.

Thanks for the tip! We may purchases a license for that reduced price.

**Comment by SBCGames** [comment]
New version supports character maps (Spriter Pro feature)

**Comment by enriqueto** [comment]
wow! amazing! we'll try it asap
