### ISSUE TITLE
SCON (JSON) format does not support tags

### ISSUE THREAD

**Issue by andiCR** [SBCGames/Spriter-Player-for-Phaser#6]
I just noticed that the code does not support it. I am coding directly on js so I won't be able to turn in my code, but basically implemented the getTag function:
```
SpriterJSON.prototype.getTag = function (element) {
    return new Spriter.Item(this.parseInt(element, "id"), this.parseString(element, "name"));
};
```
and on Loader.prototype.loadTags, I hacked a way to get the child nodes. This probably breaks xml loading but im just using json.
`            var tagDefs = tags;//tags.getChildNodes(0, "i");`
getChildNodes(0, "i") does not work for json files for some reason. Looking at the source, i think the variables might also be screwed.

**Comment by SBCGames** [comment]
There is problem with structure of JSON export from Spriter. While structure for XML and JSON is all the same, there is difference when it comes to tag definition. I am sure it is not by design - it is bug (so, I skipped implementation for JSON temporarily).

This is reason, why your patch did not work - there is missing "i" tag/property in JSON export.

 Nice thing about loader was, that it did not have to know, whether it works with JSON or XML. Now, I will have to add some special testing... I will look at it in next days.

**Comment by SBCGames** [comment]
Should work now... there are also so stupid bugs in JSON export like typos: "valline" instead of "varline" ... uff.
